### ISSUE TITLE
Nothing saves after I edit the JSON file

### ISSUE THREAD

**Issue by Cpolley** [Esri/ago-assistant#161]
It seems I cannot get anything to save using ago-assistant. I'm trying to update the type keywords for the location tracking and it won't save. I have done this before and everything worked fine not nothing saves.

**Comment by ecaldwell** [comment]
I see the same thing. It's caused by improper parsing of the submitted JSON and is only failing for array based properties like `typeKeywords` and `tags` (e.g. changing the `title` still works fine). This is fixed in #160.

**Comment by Cpolley** [comment]
@ecaldwell is there a work around. I have Location Tracking feature service working on my server and I needed to create to more for two different areas as well as different states, do you know of a work around or a timeframe ESRI's team will fix this issue?

**Comment by rwmajor2** [comment]
@Cpolley A new version 2.7.1 has been pushed to production.  Clear your web browser cache and try again.  If everything checks out, please close this issue.  Thanks.

**Comment by Cpolley** [comment]
@rwmajor2 I hate to say the issue still exists and this is a huge issue when we use the Location Tracking via our ArcGIS Server within or organization.

**Comment by Cpolley** [comment]
You can edit and change the title and save as normal, But you cannot change and save when updating TypeKeywords.

**Comment by rwmajor2** [comment]
Can you detailed exactly what you are trying to do?  Can you give us an example of Type Keywords you are trying to add?  I do know that there are some Type Keywords that are "reserved" and can not be manipulated via the REST API (i.e. only set by the underlying Portal environment).

**Comment by Cpolley** [comment]
I took the Location Tracking Template added the feature class to my database hen published to my server. I open Arcgis.com which I done before and added the rest URL then I go to ago-assistant and add the type keywords "Collector", and "Location Tracking", between the appropriate other keywords I then click save and I get the green check mark and then add the later to my map and go to the details page and check mark Location tracking but it is not there as an option so I go back ago-assistant look at the json and it does not show what I added so I did it again and refreshed the page it it goes away. I even tried the same process with portal as well and still no luck. I have one running for about 8 months now and it tracks well right into my geodatabase as well as I run a script to copy the data to a history log every night. I just need to create to more and now there seems to be a problem.

**Comment by ecaldwell** [comment]
Are you able to change anything else on the item like `tags`? I just tested and was able to add `Collector` and `Location Tracking` as new `typeKeywords` on a web map. Maybe there's another issue at play here?

**Comment by ecaldwell** [comment]
Another enhancement that may help with these workflows is to refresh the JSON view after a successful change (i.e. green check mark). This way you can immediately see if your changes took or if there is some backend reservation preventing the change.

**Comment by jlholder** [comment]
I'm still having the same issue - none of my updates directly to the JSON are saving. We've set up a second web adaptor and simply want to increment our rest endpoints to the new location, swapping from 
https://domain/arcgis/rest/services/ to https://domain/arcgis2/rest/services.

I can successfully update the URL when is it added directly to a map, but we typically save secure services w/ credentials as map image layers, feature layers, etc. and my edits directly in the JSON to the sourceUrl is not working. I can edit, save, and the "Updated Successfully!" message appears, but when I refresh the page or look at the item's details, no change.

**Comment by ecaldwell** [comment]
@jlholder Does your service have an `itemId` associated with it? You could try removing that to see if the url change sticks.

**Comment by slibby** [comment]
@jlholder If you saved the item with secured credentials, updating the URL will not work, as the backend saves a reference to that service URL and it cannot be updated through the UI or the REST API.

Unfortunately for that case, your answer would be to re-register each service with embedded credentials, which will generate a new item ID and service URL, and replace the URL/itemIDs in your web map with those new values.

**Comment by jlholder** [comment]
@slibby That matches up with what I'm seeing. When the service is secured, there is a Url and a SourceUrl, which I cannot update. But, when the service is not secured, I can update the Url. Thanks for the clarity.
